[project]
name = "rl-algos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "catppuccin-jupyterlab>=0.2.5",
    "hmmlearn>=0.3.3",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "jupyter-contrib-nbextensions>=0.7.0",
    "jupyterlab>=4.5.7",
    "jupyterlab-vim>=4.1.4",
    "jupyterthemes>=0.20.0",
    "lab>=8.9",
    "matplotlib>=3.10.9",
    "nibabel>=5.4.2",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pandoc>=2.4",
    "pymc>=5.28.5",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "tqdm>=4.67.3",
]
