---
title: "gng_m4"
output: html_notebook
---
so basically I can write stuff here.
##################
#### HBayesDM ####
##################

block 1 hta done

##########
## HTA ###

```{r}
library(hBayesDM)
b1hta_m4 <- gng_m4(
  data = "b1_hta_gngm4.txt",
  niter = 6000,
  nwarmup = 1500,
  nchain = 3,
  ncore = 2,
  vb = FALSE,
  modelRegressor = FALSE
)
```

```{r}
b2hta_m4 <- gng_m4(
  data = "b2_hta_gngm4.txt",
  niter = 6000, 
  nwarmup = 1500,
  nchain = 3,
  ncore = 2,
  vb = FALSE,
  modelRegressor = FALSE
)
```

```{r}
#Block 3v1 hta
library(hBayesDM)
b3v1hta_m4 <- gng_m4(
  data = "b3v1_hta_gngm4.txt",
  niter = 6000, 
  nwarmup = 1500,
  nchain = 3,
  ncore = 2,
  vb = FALSE,
  modelRegressor = FALSE
)
```

```{r}
library(hBayesDM)
b3v2hta_m4 <- gng_m4(
  data = "b3v2_hta_gngm4.txt",
  niter = 6000, 
  nwarmup = 1500,
  nchain = 3,
  ncore = 2,
  vb = FALSE,
  modelRegressor = FALSE
)
```

```{r}
b4hta_m4 <- gng_m4(
  data = "b4_hta_gngm4.txt",
  niter = 6000, 
  nwarmup = 1500,
  nchain = 3,
  ncore = 2,
  vb = FALSE,
  modelRegressor = FALSE
)
```

###########
### LTA ###

# Block 1 lta
```{r}
library(hBayesDM)
b1lta_m4 <- gng_m4(
  data = "b1_lta_gngm4.txt",
  niter = 6000, 
  nwarmup = 1500,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```

```{r}
b2lta_m4 <- gng_m4(
  data = "b2_lta_gngm4.txt",
  niter = 6000, 
  nwarmup = 1500,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```

```{r}
b3v1lta_m4 <- gng_m4(
  data = "b3v1_lta_gngm4.txt",
  niter = 6000, 
  nwarmup = 1500,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```

```{r}
b3v2lta_m4 <- gng_m4(
  data = "b3v2_lta_gngm4.txt",
  niter = 6000, 
  nwarmup = 1500,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```

```{r}
b4lta_m4 <- gng_m4(
  data = "b4_lta_gngm4.txt",
  niter = 6000, 
  nwarmup = 1500,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```


