---
title: "HbayesDM"
output: html_notebook
---

so basically I can write stuff here.
##################
#### HBayesDM ####
##################

block 1 hta done

##########
## HTA ###

# Block 2 hta
```{r}
library(hBayesDM)
# b2hta_m1 <- gng_m1(
#   data = "b2_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b2hta_m2 <- gng_m2(
#   data = "b2_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b2hta_m3 <- gng_m3(
#   data = "b2_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )

b2hta_m4 <- gng_m4(
  data = "b2_hta_gng.txt",
  niter = 4000, 
  nwarmup = 1000,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```

#Block 3v1 hta
```{r}
# b3v1hta_m1 <- gng_m1(
#   data = "b3v1_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b3v1hta_m2 <- gng_m2(
#   data = "b3v1_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b3v1hta_m3 <- gng_m3(
#   data = "b3v1_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )

b3v1hta_m4 <- gng_m4(
  data = "b3v1_hta_gng.txt",
  niter = 4000, 
  nwarmup = 1000,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```
#Block 3v2 hta
```{r}
# b3v2hta_m1 <- gng_m1(
#   data = "b3v2_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b3v2hta_m2 <- gng_m2(
#   data = "b3v2_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b3v2hta_m3 <- gng_m3(
#   data = "b3v2_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )

b3v2hta_m4 <- gng_m34(
  data = "b3v2_hta_gng.txt",
  niter = 4000, 
  nwarmup = 1000,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```
#Block 4 hta
```{r}
# b4hta_m1 <- gng_m1(
#   data = "b4_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b4hta_m2 <- gng_m2(
#   data = "b4_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b4hta_m3 <- gng_m3(
#   data = "b4_hta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )

b4hta_m4 <- gng_m4(
  data = "b4_hta_gng.txt",
  niter = 4000, 
  nwarmup = 1000,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```


##########
## LTA ###

# Block 1 lta
```{r}
# b1lta_m1 <- gng_m1(
#   data = "b1_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b1lta_m2 <- gng_m2(
#   data = "b1_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b1lta_m3 <- gng_m3(
#   data = "b1_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )

b1lta_m4 <- gng_m4(
  data = "b1_lta_gng.txt",
  niter = 4000, 
  nwarmup = 1000,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```

# Block 2 lta
```{r}
# b2lta_m1 <- gng_m1(
#   data = "b2_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b2lta_m2 <- gng_m2(
#   data = "b2_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b2lta_m3 <- gng_m3(
#   data = "b2_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )

b2lta_m4 <- gng_m4(
  data = "b2_lta_gng.txt",
  niter = 4000, 
  nwarmup = 1000,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```

#Block 3v1 lta
```{r}
# b3v1lta_m1 <- gng_m1(
#   data = "b3v1_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b3v1lta_m2 <- gng_m2(
#   data = "b3v1_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b3v1lta_m3 <- gng_m3(
#   data = "b3v1_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )

b3v1lta_m4 <- gng_m4(
  data = "b3v1_lta_gng.txt",
  niter = 4000, 
  nwarmup = 1000,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```
#Block 3v2 lta
```{r}
# b3v2lta_m1 <- gng_m1(
#   data = "b3v2_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b3v2lta_m2 <- gng_m2(
#   data = "b3v2_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b3v2lta_m3 <- gng_m3(
#   data = "b3v2_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )

b3v2lta_m4 <- gng_m34(
  data = "b3v2_lta_gng.txt",
  niter = 4000, 
  nwarmup = 1000,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```
#Block 4 lta
```{r}
# b4lta_m1 <- gng_m1(
#   data = "b4_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b4lta_m2 <- gng_m2(
#   data = "b4_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )
# 
# b4lta_m3 <- gng_m3(
#   data = "b4_lta_gng.txt",
#   niter = 4000, 
#   nwarmup = 1000,
#   nchain = 3,
#   ncore = 1,
#   vb = FALSE,
#   modelRegressor = FALSE
# )

b4lta_m4 <- gng_m4(
  data = "b4_lta_gng.txt",
  niter = 4000, 
  nwarmup = 1000,
  nchain = 3,
  ncore = 1,
  vb = FALSE,
  modelRegressor = FALSE
)
```